### PR TITLE
init new dev area

### PR DESCRIPTION
**Pull request by bewest**
New dev area.

### CODE REVIEW

**Comment by oskarpearson** [comment]
Once some PRs have accumulated against the new dev area, we get ready for a release.

**Comment by oskarpearson** [comment]
The docs in stdprojectexample say that the merge happens on the git command line; I'm going to do it as per the docs, and then merge on the UI here if required.

I'm doing things this way because that way the merge is local to my box, and if I mess something up I can reset git and get back to how things were.

**Comment by bewest** [comment]
Nicely done.  Regarding doing merge via commandline versus through the Github UI/PR: depending on which you do, you'll likely have to delete the inverse `dev` branch.  Eg, if you merge through the Github UI, you might have a stale `dev` branch on your local box which will need to be deleted before re-creating it.  Vice versa for doing it on commandline, unless dev's changes to master automatically closes the PR, you'll have to manually destroy and recreate the new dev/planning PR.

**Comment by bewest** [comment]
I've added @oskarpearson to bunch of projects on pypi (all except openaps), would prefer to do another few practice runs before doing that one.

The basic aim here is to make master the default version, to have all tags in the master branch, to make all tags match between pypi and github, and to use dev to queue up for new releases.  Well done, again. :-)

**Pull request merged**
